User.create({id:2, password:"123456",email:"user@gmail.com",user_coordinate:[2,3]})
User.create({id:3, password:"123456",email:"user1@gmail.com",user_coordinate:[2,4]})
User.create({id:4, password:"123456",email:"user2@gmail.com",user_coordinate:[2,5]})
User.create({id:5, password:"123456",email:"user3@gmail.com",user_coordinate:[2,6]})
User.create({id:6, password:"123456",email:"user4@gmail.com",user_coordinate:[2,7]})
User.create({id:7, password:"123456",email:"user5@gmail.com",user_coordinate:[2,8]})
User.create({id:8, password:"123456",email:"user6@gmail.com",user_coordinate:[2,9]})
User.create({id:9, password:"123456",email:"user7@gmail.com",user_coordinate:[1,3]})
User.create({id:10, password:"123456",email:"user8@gmail.com",user_coordinate:[3,3]})
User.create({id:11, password:"123456",email:"user9@gmail.com",user_coordinate:[4,3]})

Product.create({title:'Sneaker',coordinates:[2,3],tags:["sneaker","men"],price:100,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Shirts',coordinates:[2,4],tags:["shirt","women"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Socks',coordinates:[2,5],tags:["socks","winter"],price:300,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Scarf',coordinates:[2,6],tags:["scarf","summer"],price:400,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Jacket',coordinates:[2,7],tags:["jacket","just-in"],price:500,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Sweater',coordinates:[2,8],tags:["sweater","clearence"],price:600,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Beachwear',coordinates:[2,9],tags:["beachwear","accessories"],price:700,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Sandals',coordinates:[2,10],tags:["sandals","fall"],price:800,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'Shorts',coordinates:[3,3],tags:["shorts","spring"],price:900,description:"this is the product",rfid:"263635DFDFDEEDGG"})

Type.create({name: 'Men', description:"Men's Clothing",tags:["men"]})
Type.create({name: 'Women', description:"Women's Clothing",tags:["women"]})
Type.create({name: 'Winter', description:"Winter Clothing",tags:["winter"]})
Type.create({name: 'Summer', description:"Summer Clothing",tags:["summer"]})
Type.create({name: 'Spring', description:"Spring Clothing",tags:["spring"]})
Type.create({name: 'Fall', description:"Fall Clothing",tags:["fall"]})
Type.create({name: 'Sale', description:"Sale Clothing",tags:["sale"]})
Type.create({name: 'Clearence', description:"Clearence Clothing",tags:["clearence"]})
Type.create({name: 'Just In', description:"Just In Clothing",tags:["just-in"]})
Type.create({name: 'Unisex', description:"Unisex Clothing",tags:["unisex"]})
Type.create({name: 'Accessories', description:"Accessories",tags:["accessorcies"]})


Area.create({name: 'Area 1', description:"tango",coordinates:[[0, 0],[3, 6],[6, 3],[3, 1],[0,0]]})
Area.create({name: 'Area 2',description:"whiskey",coordinates:[[3, 3],[6, 12],[12, 6],[6, 4],[3,3]]})
Area.create({name: 'Area 3', description:"foxtrot",coordinates:[[6, 6],[12, 14],[14, 6],[6, 5],[6,6]]})
Area.create({name: 'Area 4',description:"alpha",coordinates:[[8, 8],[14, 16],[16, 8],[6, 8],[8,8]]})
Area.create({name: 'Area 5', description:"beta",coordinates:[[10, 10],[16, 18],[18, 10],[8, 10],[10,10]]})
Area.create({name: 'Area 6',description:"orion",coordinates:[[12, 12],[18, 20],[20, 12],[10, 12],[10,10]]})
Area.create({name: 'Area 7',description:"maximus",coordinates:[[14, 14],[20, 22],[22, 14],[12, 14],[14,14]]})
Area.create({name: 'Area 8', description:"hercules",coordinates:[[16, 16],[22, 24],[24, 16],[14, 16],[16,16]]})
Area.create({name: 'Area 9', description:"poseidon",coordinates:[[18, 18],[24, 26],[26, 18],[16, 18],[18,18]]})
Area.create({name: 'Area 10',description:"hera",coordinates:[[20, 20],[26, 28],[28, 20],[18, 20],[20,20]]})
