User.create({id:2, password:"123456",email:"user@gmail.com",user_coordinate:[2,3]})
User.create({id:3, password:"123456",email:"user1@gmail.com",user_coordinate:[2,4]})
User.create({id:4, password:"123456",email:"user2@gmail.com",user_coordinate:[2,5]})
User.create({id:5, password:"123456",email:"user3@gmail.com",user_coordinate:[2,6]})
User.create({id:6, password:"123456",email:"user4@gmail.com",user_coordinate:[2,7]})
User.create({id:7, password:"123456",email:"user5@gmail.com",user_coordinate:[2,8]})
User.create({id:8, password:"123456",email:"user6@gmail.com",user_coordinate:[2,9]})
User.create({id:9, password:"123456",email:"user7@gmail.com",user_coordinate:[1,3]})
User.create({id:10, password:"123456",email:"user8@gmail.com",user_coordinate:[3,3]})
User.create({id:11, password:"123456",email:"user9@gmail.com",user_coordinate:[4,3]})

Product.create({title:'the product',tags:["metal"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product1',tags:["indie"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product2',tags:["reggae"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product3',tags:["dance"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product4',tags:["rock"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product5',tags:["soul"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product6',tags:["accapella"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product8',tags:["show"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})
Product.create({title:'the product9',tags:["edm"],price:200,description:"this is the product",rfid:"263635DFDFDEEDGG"})

Type.create({name: 'metal', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'opera', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'edm', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'show', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'accapella', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'dance', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'rock', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'soul', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'reggae', description:"a leather thing for feet",tags:["shoes","footwear"]})
Type.create({name: 'indie', description:"a leather thing for feet",tags:["shoes","footwear"]})


Admin.create(id:1, password:"12356",email:"admin1@gmail.com", admin_coordinate:[2,3])
Admin.create(id:2, password:"12356",email:"admin2@gmail.com", admin_coordinate:[2,4])
Admin.create(id:3, password:"12356",email:"admin3@gmail.com", admin_coordinate:[2,5])
Admin.create(id:4, password:"12356",email:"admin4@gmail.com", admin_coordinate:[2,6])
Admin.create(id:5, password:"12356",email:"admin5@gmail.com", admin_coordinate:[2,7])
Admin.create(id:6, password:"12356",email:"admin6@gmail.com", admin_coordinate:[2,8])
Admin.create(id:7, password:"12356",email:"admin7@gmail.com", admin_coordinate:[2,9])
Admin.create(id:8, password:"12356",email:"admin8@gmail.com", admin_coordinate:[3,3])
Admin.create(id:9, password:"12356",email:"admin9@gmail.com", admin_coordinate:[4,3])
Admin.create(id:10, password:"12356",email:"admin11@gmail.com", admin_coordinate:[5,3])
Admin.create(id:11, password:"12356",email:"admin12@gmail.com", admin_coordinate:[6,3])
