development:
  adapter: postgresql
  encoding: unicode
  database: arei_app_api
  pool: 5
  username:
  password: "12345"

test:
  adapter: postgresql
  encoding: unicode
  database: arei_app_api
  pool: 5
  username:
  password: "12345"
